//
//  AutoContinueShareViewController.swift
//  RNShareMenu
//
//  DO NOT EDIT THIS FILE. IT WILL BE OVERRIDEN BY NPM OR YARN.
//
//  Created by Johannes Klein on 17/03/2026.
//

import UIKit
import RNShareMenu

@available(iOSApplicationExtension, unavailable)
class AutoContinueShareViewController: ShareViewController {
  private var didAutoContinue = false

  private func autoContinueIfNeeded() {
    guard !didAutoContinue else { return }
    didAutoContinue = true

    guard let items = extensionContext?.inputItems as? [NSExtensionItem] else {
      cancelRequest()
      return
    }

    handlePost(items)
  }

  override func viewDidLoad() {
    super.viewDidLoad()

    let blankView = UIView()
    blankView.backgroundColor = .clear
    blankView.alpha = 0
    view = blankView
  }

  override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    autoContinueIfNeeded()
  }
}

