//
//  ReactShareViewController.swift
//  RNShareMenu
//
//  DO NOT EDIT THIS FILE. IT WILL BE OVERRIDEN BY NPM OR YARN.
//
//  Created by Gustavo Parreira on 29/07/2020.
//

import RNShareMenu
import UIKit

@available(iOSApplicationExtension, unavailable)
private final class ShareExtensionReactNativeFactoryDelegate: RCTDefaultReactNativeFactoryDelegate {
  override func sourceURL(for bridge: RCTBridge!) -> URL! {
#if DEBUG
    return RCTBundleURLProvider.sharedSettings()
      .jsBundleURL(forBundleRoot: "index.share")
#else
    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }

  override func bundleURL() -> URL! {
#if DEBUG
    return RCTBundleURLProvider.sharedSettings()
      .jsBundleURL(forBundleRoot: "index.share")
#else
    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
}

@available(iOSApplicationExtension, unavailable)
class ReactShareViewController: ShareViewController, ReactShareViewDelegate {
  private let reactNativeFactoryDelegate = ShareExtensionReactNativeFactoryDelegate()
  private lazy var reactNativeFactory: RCTReactNativeFactory = {
    reactNativeFactoryDelegate.dependencyProvider = RCTAppDependencyProvider()
    return RCTReactNativeFactory(delegate: reactNativeFactoryDelegate)
  }()

  private var didAutoContinueInApp = false

  private var isAutoContinueInAppEnabled: Bool {
    // Opt-in: bypass extension UI and immediately forward to the host app.
    return (Bundle.main.object(forInfoDictionaryKey: SHARE_MENU_AUTO_CONTINUE_IN_APP_KEY) as? Bool) == true
  }

  private func autoContinueInAppIfNeeded() {
    // Run once per presentation to avoid duplicate writes/opens.
    guard isAutoContinueInAppEnabled, !didAutoContinueInApp else { return }
    didAutoContinueInApp = true

    guard let items = extensionContext?.inputItems as? [NSExtensionItem] else {
      cancelRequest()
      return
    }

    handlePost(items)
  }

  override func viewDidLoad() {
    super.viewDidLoad()

    if isAutoContinueInAppEnabled {
      // Keep the extension visually blank to avoid any UI flash during the handoff.
      let blankView = UIView()
      blankView.backgroundColor = .clear
      blankView.alpha = 0
      self.view = blankView
      return
    }

    let rootView = reactNativeFactory.rootViewFactory.view(
      withModuleName: "ShareMenuModuleComponent",
      initialProperties: nil,
      launchOptions: nil
    )

    rootView.backgroundColor = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
    backgroundColorSetup: if let backgroundColorConfig = Bundle.main.infoDictionary?[REACT_SHARE_VIEW_BACKGROUND_COLOR_KEY] as? [String:Any] {
      if let transparent = backgroundColorConfig[COLOR_TRANSPARENT_KEY] as? Bool, transparent {
        rootView.backgroundColor = nil
        break backgroundColorSetup
      }

      let red = backgroundColorConfig[COLOR_RED_KEY] as? Float ?? 1
      let green = backgroundColorConfig[COLOR_GREEN_KEY] as? Float ?? 1
      let blue = backgroundColorConfig[COLOR_BLUE_KEY] as? Float ?? 1
      let alpha = backgroundColorConfig[COLOR_ALPHA_KEY] as? Float ?? 1

      rootView.backgroundColor = UIColor(red: CGFloat(red), green: CGFloat(green), blue: CGFloat(blue), alpha: CGFloat(alpha))
    }

    self.view = rootView

    ShareMenuReactView.attachViewDelegate(self)
  }

  override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    // Trigger before the extension becomes visible on screen.
    autoContinueInAppIfNeeded()
  }

  override func viewDidDisappear(_ animated: Bool) {
    if isAutoContinueInAppEnabled {
      return
    }

    cancel()
    ShareMenuReactView.detachViewDelegate()
  }

  func loadExtensionContext() -> NSExtensionContext {
    return extensionContext!
  }

  func openApp() {
    self.openHostApp()
  }

  func continueInApp(with items: [NSExtensionItem], and extraData: [String:Any]?) {
    handlePost(items, extraData: extraData)
  }
}
